# .github/workflows/main.yaml
name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  main-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Start Main Flow
        run: |
          echo "This is main flow"
          date

  subjob1:
    needs: main-flow
    uses: ./.github/workflows/subjob1.yaml

  subjob2:
    needs: subjob1
    uses: ./.github/workflows/subjob2.yaml
