# .github/workflows/main.yaml
name: Main Flow

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Main job - Print message
        run: echo "This is the main workflow"

      - name: Echo timestamp (Main workflow)
        run: |
          timestamp=$(date +'%H:%M:%S')
          echo "This is the main workflow execution completed at $timestamp"
          
  call-subjob1:
    needs: main-job  # Ensure this job runs after the main-job completes
    uses: ./.github/workflows/subjob1.yaml