# .github/workflows/subjob1.yaml
name: Child Job 1

on:
  workflow_call:  # Allows this workflow to be called from other workflows
    inputs:
      message:
        description: 'Message for the subjob'
        required: false
        default: 'This is child job 1'

jobs:
  subjob1:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: |
          echo "${{ inputs.message }}"
          timestamp=$(date +'%H:%M:%S')
          echo "This is child job 1 execution completed at $timestamp"
